{% set name = "gstools" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12e822136fcfec3b6d06d1a261428c1360ffeab766c6da3a8ff2efd08ae363d7

build:
  skip: true  # [python_impl == 'pypy']
  number: 0
  script_env:
    - GSTOOLS_BUILD_PARALLEL=1
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0                           # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools >=64
    - setuptools_scm >=7
    - cython >=3.0
    - numpy
    - extension-helpers
  run:
    - python
    - numpy >=1.20.0
    - scipy >=1.1.0
    - emcee >=3.0.0
    - hankel >=1.0.0
    - pyevtk >=1.1.1
    - meshio >=5.1.0

test:
  imports:
    - gstools
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/GeoStat-Framework/GSTools
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: 'GSTools: A geostatistical toolbox.'
  description: |
    GeoStatTools provides geostatistical tools for various purposes:
    - random field generation
    - simple, ordinary, universal and external drift kriging
    - conditioned field generation
    - incompressible random vector field generation
    - (automatted) variogram estimation and fitting
    - directional variogram estimation and modelling
    - data normalization and transformation
    - many readily provided and even user-defined covariance models
    - metric spatio-temporal modelling
    - plotting and exporting routines
  doc_url: https://gstools.readthedocs.io
  dev_url: https://github.com/GeoStat-Framework/GSTools

extra:
  recipe-maintainers:
    - MuellerSeb
    - LSchueler
